### ISSUE TITLE
Use holochain version instead of rev in nix file

### ISSUE THREAD

**Issue by jost-s** [holochain-engineers/starter-ui#1]
Hi @nphias, just came across your repo here, cool stuff you're making it public!

There's an easier way to use a specific Holochain version from cachix:
```nix
let
  holonixPath = builtins.fetchTarball "https://github.com/holochain/holonix/archive/main.tar.gz";
  holonix = import (holonixPath) {
    holochainVersionId = "v0_0_121";
  };
...
```

In case you don't care, just close this issue ;-)

**Comment by nphias** [comment]
done ... @jost-s let me know if the happ works for you?

**Comment by nphias** [comment]
done ... @jost-s let me know if the happ works for you?
